{% set version = "2.1.4" %}

package:
  name: gmpy2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gmpy2/gmpy2-{{ version }}.tar.gz
  sha256: 37a9959dae0d008fa750cbcdedd43518b7a1bdaa95a19f30effc6d045ad7adbd
  patches:
    - win_setup.diff

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python
    - pip
  run:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python

test:
  imports:
    - gmpy2

about:
  home: https://pypi.python.org/pypi/gmpy2
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x

extra:
  recipe-maintainers:
    - isuruf
