{% set version = "2.2.0" %}

package:
  name: gmpy2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gmpy2/gmpy2-{{ version }}.tar.gz
  sha256: e19e62dfeb1e4a57079f0bf51c51dec30633d9fe9e89cb9a083e05e4823afa70
  patches:
    - patches/0001-set-flags-necessary-for-windows-in-setup.py.patch
    # Currently, there is no GMP build on windows, see
    # https://github.com/conda-forge/gmp-feedstock/issues/34.
    # We need to disable newer features of GMP that are not available in MPIR.
    - patches/0002-Disable-code-path-not-supported-by-MPIR.patch  # [win]
    # backport patch for 3.12 compatibility from upstream, see
    # https://github.com/aleaxit/gmpy/issues/446#issuecomment-1784443227
    - patches/0003-compatibility-for-python-3.12.patch

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python
    - pip
  run:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python

test:
  imports:
    - gmpy2

about:
  home: https://pypi.python.org/pypi/gmpy2
  dev_url: https://github.com/aleaxit/gmpy
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: GMP/MPIR, MPFR, and MPC interface to Python

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
