{% set version = "2.1.0" %}

package:
  name: gmpy2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gmpy2/gmpy2-{{ version }}.tar.gz
  sha256: d606f89674257dceb6c54d173bb75b90f2e07e66598e6654eb1146e60ddc9d72
  patches:
    - win_setup.diff

build:
  number: 0
  script:
    - python setup.py install

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python
    - pip
  run:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python

test:
  imports:
    - gmpy2

about:
  home: https://pypi.python.org/pypi/gmpy2
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x

extra:
  recipe-maintainers:
    - isuruf
