{% set version = "2.1.5" %}

package:
  name: gmpy2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gmpy2/gmpy2-{{ version }}.tar.gz
  sha256: bc297f1fd8c377ae67a4f493fc0f926e5d1b157e5c342e30a4d84dc7b9f95d96
  patches:
    - win_setup.diff
    # Currently, there is no GMP build on windows, see
    # https://github.com/conda-forge/gmp-feedstock/issues/34.
    # We need to disable newer features of GMP that are not available in MPIR.
    - 0001-Disable-code-path-not-supported-by-MPIR.patch  # [win]

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python
    - pip
  run:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python

test:
  imports:
    - gmpy2

about:
  home: https://pypi.python.org/pypi/gmpy2
  dev_url: https://github.com/aleaxit/gmpy
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: GMP/MPIR, MPFR, and MPC interface to Python

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
