{% set version = "2.2.1" %}

package:
  name: gmpy2
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gmpy2/gmpy2-{{ version }}.tar.gz
  sha256: e83e07567441b78cb87544910cb3cc4fe94e7da987e93ef7622e76fb96650432

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - gmp
    - mpfr
    - mpc
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - gmpy2

about:
  home: https://pypi.python.org/pypi/gmpy2
  dev_url: https://github.com/aleaxit/gmpy
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: GMP/MPIR, MPFR, and MPC interface to Python

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
