appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RPxsl/inSAd1nUROiY0inXJGy1uGUmbKK1/ulOAEncicBtkQ5bICOW4i1S28jdkAelwLgQOj6qOeRBFOrT7Zr22pLJiop38l6XOOXdbe44+LWPtjGorJTXPhFPYAf4rHUHxznMSSfkb9ABjI8EGew7Dipp35f5VApgAPE1sFDe9VRl5L0G0z1MCNlRNSYXktxdOgYZZNjs9j5IWKfROPSkKGv1Q1J1SdWzIhj/MW4QqFGBKMLVkvwNOFt+xY0DExhyRY6EzpOLbosSQtsbzL47WBiMXTGh9rUl+wp6b7vwgHCDKCHdm9GLW3jY+5nzblVoFwQuiUwmH6KO9qa3x0FHmbhR9tCbuQyE5TEBSMMtDcM0h00zbi03yID2RUP/AUCoC4G4OFSImJjTwEJwWIMu/8cKEm3gc+vQGKND+0t2OBu6qb6SLB2XnyAVumc6AUUwK+7zX5mV+xvGOnelTGDXBtM+nQKAC4mkak+W6/qQcp/uwRRQrlmrYRfjB4Tech+MrON/Iof1SI3Nas8+lXJRCoEi+YTEKCnRIhj2RXSGjJoTBVbI1qAtrj0ytirDd1xvw5qsBQYMZuiYQnez7Ii97z7sqEoWPSWNFHx1lfayf8c1uJEvUbd+K+4oyb1Z9NqjUMHR+ycsrRk1D6kIWib+3hMH0p5QUt/PuUkdSAC5E=}
